/**
 * Environment Setup Helper
 * Helps you create the .env file with Supabase credentials
 */

import { writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const envPath = join(__dirname, '..', '.env');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

console.log('\n╔══════════════════════════════════════════════════════════╗');
console.log('║     MTU SIWES - Environment Setup Helper               ║');
console.log('╚══════════════════════════════════════════════════════════╝\n');

console.log('This script will help you create a .env file for the server.\n');
console.log('You can find your Supabase credentials in:');
console.log('  https://supabase.com/dashboard/project/jcxshefzlzjwsxmifmqd/settings/api\n');

if (existsSync(envPath)) {
  const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
  if (overwrite.toLowerCase() !== 'y') {
    console.log('\nCancelled. Existing .env file preserved.\n');
    rl.close();
    process.exit(0);
  }
}

const supabaseUrl = await question('Enter your Supabase URL (e.g., https://xxxxx.supabase.co): ');
const serviceRoleKey = await question('Enter your Supabase Service Role Key: ');
const emailUser = await question('Enter your email for sending (Gmail, optional): ') || '';
const emailPass = await question('Enter your email app password (optional): ') || '';

const envContent = `# MTU SIWES Server Environment Variables
# Generated by setup script

# Supabase Configuration
SUPABASE_URL=${supabaseUrl.trim()}
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey.trim()}

# Email Configuration (for email verification)
EMAIL_USER=${emailUser.trim()}
EMAIL_PASS=${emailPass.trim()}

# Server Configuration
PORT=3001
FRONTEND_URL=http://localhost:8080
NODE_ENV=development
`;

try {
  writeFileSync(envPath, envContent);
  console.log('\n✅ .env file created successfully!\n');
  console.log(`Location: ${envPath}\n`);
  console.log('You can now run the createAdmin script:\n');
  console.log('  node server/scripts/createAdmin.js admin@mtu.edu.ng Admin123! "Admin User"\n');
} catch (error) {
  console.error('\n❌ Error creating .env file:', error.message);
  process.exit(1);
} finally {
  rl.close();
}

























